### ISSUE TITLE
Basic ValidJSON Question

### ISSUE THREAD

**Issue by metaskills** [braintrustdata/autoevals#105]
Using the TypeScript library. How do I pass a schema to `ValidJSON`? I tried passing a `schema` or `metadata.schema` property in my data. Also trie `ValidJSON({schema})` and nothing in Cursor fix with TypeScript is working.

**Comment by metaskills** [comment]
Example code:

```javascript
Eval("Extract Claims", {
  data: () => {
    return [
      {
        input: claim,
        expected: 1,
      },
    ];
  },
  task: async (input) => {
    return extractClaims(input);
  },
  scores: [ValidJSON],
});
```

**Comment by metaskills** [comment]
Think I got it with `scores: [ValidJSON.partial({ schema: schema })],`

**Comment by ankrgyl** [comment]
Yep `partial` should solve it! Were you able to sort it out?

**Comment by metaskills** [comment]
Thanks. Technically no, any schema I pass seems to be ignored. Still testing but I'm not seeing it be used.

**Comment by metaskills** [comment]
Yup, I'm good. Thank you!
