### ISSUE TITLE
Question about deps

### ISSUE THREAD

**Issue by transitive-bullshit** [braintrustdata/autoevals#61]
![CleanShot 2024-04-07 at 18 50 38@2x](https://github.com/braintrustdata/autoevals/assets/552829/a07f6b9a-74bc-4bb8-bf0b-f6a3872f5a6b)

Should  `tsx` and `@types/node` be dev deps?

**Comment by ankrgyl** [comment]
Yes. Good catch. Happy to fix or if you feel inclined, would love a PR!
