### ISSUE TITLE
Support of Azure Open AI models and API

### ISSUE THREAD

**Issue by micky-amir** [braintrustdata/autoevals#89]
Hi,

It seems that Azure OpenAI (https://oai.azure.com/) is not supported. Is that the case?
Will be glad to add that functionality if does not exists yet

**Comment by ankrgyl** [comment]
It should work if you set an azure endpoint as the `openAiBaseUrl`. Are you seeing otherwise?

**Comment by ankrgyl** [comment]
ah ok makes sense. i think this may have changed/diverged over time. happy to help support a contribution / PR here

**Comment by mongodben** [comment]
Just did a quick PR to support Azure OpenAI https://github.com/braintrustdata/autoevals/pull/91

Please let me know what you think. We can continue the conversation on that PR.
