### ISSUE TITLE
Is there a way to access LLM token usage

### ISSUE THREAD

**Issue by shekhargulati** [braintrustdata/autoevals#96]
Thanks for the autoevals library. I was wondering if there was a way to access LLM model usage (prompt and completion tokens) after making an evaluation call. This way downstream systems can track eval token usage. I am building systems where I expose evals to the end users and want to show token usage to them. 

Let me know if there is a way to get this information. 

I know OpenAI proxy is one possible way but I want to avoid that complexity.

**Comment by ankrgyl** [comment]
The best way to do this would be to use Braintrust. If you want to just stick to using autoevals, I think you could probably monkey patch the `openai` client to capture this information yourself.

**Comment by shekhargulati** [comment]
Thanks. I monkey patched and it is working.

This is what I did. I had to monkey patch `_postprocess_response` method of `OpenAILLMClassifier`

I redefined this method in my code and capture usage and set it in score.metadata.

```python
def _new_postprocess_response(self, resp):
    if len(resp["choices"]) > 0:
        score = self._process_response(resp["choices"][0]["message"])
        score.metadata['usage'] = resp['usage']
        return score
    else:
        raise ValueError("Empty response from OpenAI")
```

Then after creating evaluator instance I set this method.

```python
evaluator = LLMClassifier()
evaluator._postprocess_response = _new_postprocess_response.__get__(evaluator)
```

**Comment by ankrgyl** [comment]
Great! That seems like a pretty reasonable solution to me.
